#!/bin/bash

#SBATCH --job-name VoxelNet
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 28
#SBATCH --gres=gpu:2
#SBATCH --time 1-00:00:00
#SBATCH --partition gpu
#SBATCH --output gpu2.out
#SBATCH --exclusive
#SBATCH --mem=128000
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

echo $SLURM_JOB_NODELIST > machine.file.$SLURM_JOBID
numnodes=`wc machine.file.$SLURM_JOBID | awk '{ print $1 }'`
echo $numnodes
module load languages/anaconda3/3.5-4.2.0-tflow-1.7
#export TMPDIR=/mnt/storage/home/ja17618/advanced-hpc-lbm/
#module load languages/anaconda2/5.0.1.tensorflow-1.6.0
source activate vox
#export I_MPI_DEBUG=5 
#module load CUDA/8.0.44-GCC-5.4.0-2.26
#export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
#module load clang-ykt/2017-07-24
#module use /mnt/storage/scratch/jp8463/modules/modulefiles
#module add OpenMPI/2.0.1-gcccuda-2016.10
#module add libs/cudnn/5.1-cuda-8.0
#module load languages/intel/2017.0
#conda info --envs
#which python
unset XDG_RUNTIME_DIR
cd $HOME
#port=$(shuf -i 20000-30000 -n 1)
port=16006
#/usr/bin/ssh -N -f -R $port:localhost:$port log-0
#/usr/bin/ssh -N -f -R $port:localhost:$port log-1
 
echo -e "\nStarting Jupyter Notebook on port ${port} on the $(hostname) server."
echo -e "\nSSH tunnel command: ssh -NL ${port}:${SLURM_JOB_NODELIST:}:${port} ${USER}@bc4login.acrc.bris.ac.uk"
echo -e "\nLocal URI: http://localhost:${port}"
jupyter-notebook --no-browser --port=${port} --ip='*'



